# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imageFilter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imageFilter.proto',
  package='imageFilter',
  syntax='proto3',
  serialized_options=b'\252\002\023ToolGood.TextFilter',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11imageFilter.proto\x12\x0bimageFilter\"%\n\x15ImageLocalGrpcRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"&\n\x16ImageUploadGrpcRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"J\n\x1aImageLocalAsyncGrpcRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\trequestId\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"K\n\x1bImageUploadAsyncGrpcRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x11\n\trequestId\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"K\n\x17ImageRequestIdGrpcReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\trequestId\x18\x03 \x01(\t\"X\n\x14ImageFilterGrpcReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\trequestId\x18\x03 \x01(\t\x12\x0e\n\x06unsafe\x18\x04 \x01(\x02\"\xa4\x01\n\x16ImageClassifyGrpcReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\trequestId\x18\x03 \x01(\t\x12\x0c\n\x04porn\x18\x04 \x01(\x02\x12\x0e\n\x06\x62loody\x18\x05 \x01(\x02\x12\x0e\n\x06hentai\x18\x06 \x01(\x02\x12\x0c\n\x04lure\x18\x07 \x01(\x02\x12\x0c\n\x04sexy\x18\x08 \x01(\x02\x12\x0e\n\x06normal\x18\t \x01(\x02\x32\x9b\x03\n\x0fImageFilterGrpc\x12Y\n\x10ImageLocalFilter\x12\".imageFilter.ImageLocalGrpcRequest\x1a!.imageFilter.ImageFilterGrpcReply\x12[\n\x11ImageUploadFilter\x12#.imageFilter.ImageUploadGrpcRequest\x1a!.imageFilter.ImageFilterGrpcReply\x12\x66\n\x15ImageLocalFilterAsync\x12\'.imageFilter.ImageLocalAsyncGrpcRequest\x1a$.imageFilter.ImageRequestIdGrpcReply\x12h\n\x16ImageUploadFilterAsync\x12(.imageFilter.ImageUploadAsyncGrpcRequest\x1a$.imageFilter.ImageRequestIdGrpcReplyB\x16\xaa\x02\x13ToolGood.TextFilterb\x06proto3'
)




_IMAGELOCALGRPCREQUEST = _descriptor.Descriptor(
  name='ImageLocalGrpcRequest',
  full_name='imageFilter.ImageLocalGrpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='imageFilter.ImageLocalGrpcRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=71,
)


_IMAGEUPLOADGRPCREQUEST = _descriptor.Descriptor(
  name='ImageUploadGrpcRequest',
  full_name='imageFilter.ImageUploadGrpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='imageFilter.ImageUploadGrpcRequest.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=111,
)


_IMAGELOCALASYNCGRPCREQUEST = _descriptor.Descriptor(
  name='ImageLocalAsyncGrpcRequest',
  full_name='imageFilter.ImageLocalAsyncGrpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='imageFilter.ImageLocalAsyncGrpcRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='imageFilter.ImageLocalAsyncGrpcRequest.requestId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='imageFilter.ImageLocalAsyncGrpcRequest.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=187,
)


_IMAGEUPLOADASYNCGRPCREQUEST = _descriptor.Descriptor(
  name='ImageUploadAsyncGrpcRequest',
  full_name='imageFilter.ImageUploadAsyncGrpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='imageFilter.ImageUploadAsyncGrpcRequest.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='imageFilter.ImageUploadAsyncGrpcRequest.requestId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='imageFilter.ImageUploadAsyncGrpcRequest.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=264,
)


_IMAGEREQUESTIDGRPCREPLY = _descriptor.Descriptor(
  name='ImageRequestIdGrpcReply',
  full_name='imageFilter.ImageRequestIdGrpcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='imageFilter.ImageRequestIdGrpcReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='imageFilter.ImageRequestIdGrpcReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='imageFilter.ImageRequestIdGrpcReply.requestId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=341,
)


_IMAGEFILTERGRPCREPLY = _descriptor.Descriptor(
  name='ImageFilterGrpcReply',
  full_name='imageFilter.ImageFilterGrpcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='imageFilter.ImageFilterGrpcReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='imageFilter.ImageFilterGrpcReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='imageFilter.ImageFilterGrpcReply.requestId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unsafe', full_name='imageFilter.ImageFilterGrpcReply.unsafe', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=431,
)


_IMAGECLASSIFYGRPCREPLY = _descriptor.Descriptor(
  name='ImageClassifyGrpcReply',
  full_name='imageFilter.ImageClassifyGrpcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='imageFilter.ImageClassifyGrpcReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='imageFilter.ImageClassifyGrpcReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='imageFilter.ImageClassifyGrpcReply.requestId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='porn', full_name='imageFilter.ImageClassifyGrpcReply.porn', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bloody', full_name='imageFilter.ImageClassifyGrpcReply.bloody', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hentai', full_name='imageFilter.ImageClassifyGrpcReply.hentai', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lure', full_name='imageFilter.ImageClassifyGrpcReply.lure', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sexy', full_name='imageFilter.ImageClassifyGrpcReply.sexy', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='normal', full_name='imageFilter.ImageClassifyGrpcReply.normal', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=598,
)

DESCRIPTOR.message_types_by_name['ImageLocalGrpcRequest'] = _IMAGELOCALGRPCREQUEST
DESCRIPTOR.message_types_by_name['ImageUploadGrpcRequest'] = _IMAGEUPLOADGRPCREQUEST
DESCRIPTOR.message_types_by_name['ImageLocalAsyncGrpcRequest'] = _IMAGELOCALASYNCGRPCREQUEST
DESCRIPTOR.message_types_by_name['ImageUploadAsyncGrpcRequest'] = _IMAGEUPLOADASYNCGRPCREQUEST
DESCRIPTOR.message_types_by_name['ImageRequestIdGrpcReply'] = _IMAGEREQUESTIDGRPCREPLY
DESCRIPTOR.message_types_by_name['ImageFilterGrpcReply'] = _IMAGEFILTERGRPCREPLY
DESCRIPTOR.message_types_by_name['ImageClassifyGrpcReply'] = _IMAGECLASSIFYGRPCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageLocalGrpcRequest = _reflection.GeneratedProtocolMessageType('ImageLocalGrpcRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGELOCALGRPCREQUEST,
  '__module__' : 'imageFilter_pb2'
  # @@protoc_insertion_point(class_scope:imageFilter.ImageLocalGrpcRequest)
  })
_sym_db.RegisterMessage(ImageLocalGrpcRequest)

ImageUploadGrpcRequest = _reflection.GeneratedProtocolMessageType('ImageUploadGrpcRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEUPLOADGRPCREQUEST,
  '__module__' : 'imageFilter_pb2'
  # @@protoc_insertion_point(class_scope:imageFilter.ImageUploadGrpcRequest)
  })
_sym_db.RegisterMessage(ImageUploadGrpcRequest)

ImageLocalAsyncGrpcRequest = _reflection.GeneratedProtocolMessageType('ImageLocalAsyncGrpcRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGELOCALASYNCGRPCREQUEST,
  '__module__' : 'imageFilter_pb2'
  # @@protoc_insertion_point(class_scope:imageFilter.ImageLocalAsyncGrpcRequest)
  })
_sym_db.RegisterMessage(ImageLocalAsyncGrpcRequest)

ImageUploadAsyncGrpcRequest = _reflection.GeneratedProtocolMessageType('ImageUploadAsyncGrpcRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEUPLOADASYNCGRPCREQUEST,
  '__module__' : 'imageFilter_pb2'
  # @@protoc_insertion_point(class_scope:imageFilter.ImageUploadAsyncGrpcRequest)
  })
_sym_db.RegisterMessage(ImageUploadAsyncGrpcRequest)

ImageRequestIdGrpcReply = _reflection.GeneratedProtocolMessageType('ImageRequestIdGrpcReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUESTIDGRPCREPLY,
  '__module__' : 'imageFilter_pb2'
  # @@protoc_insertion_point(class_scope:imageFilter.ImageRequestIdGrpcReply)
  })
_sym_db.RegisterMessage(ImageRequestIdGrpcReply)

ImageFilterGrpcReply = _reflection.GeneratedProtocolMessageType('ImageFilterGrpcReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEFILTERGRPCREPLY,
  '__module__' : 'imageFilter_pb2'
  # @@protoc_insertion_point(class_scope:imageFilter.ImageFilterGrpcReply)
  })
_sym_db.RegisterMessage(ImageFilterGrpcReply)

ImageClassifyGrpcReply = _reflection.GeneratedProtocolMessageType('ImageClassifyGrpcReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECLASSIFYGRPCREPLY,
  '__module__' : 'imageFilter_pb2'
  # @@protoc_insertion_point(class_scope:imageFilter.ImageClassifyGrpcReply)
  })
_sym_db.RegisterMessage(ImageClassifyGrpcReply)


DESCRIPTOR._options = None

_IMAGEFILTERGRPC = _descriptor.ServiceDescriptor(
  name='ImageFilterGrpc',
  full_name='imageFilter.ImageFilterGrpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=601,
  serialized_end=1012,
  methods=[
  _descriptor.MethodDescriptor(
    name='ImageLocalFilter',
    full_name='imageFilter.ImageFilterGrpc.ImageLocalFilter',
    index=0,
    containing_service=None,
    input_type=_IMAGELOCALGRPCREQUEST,
    output_type=_IMAGEFILTERGRPCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ImageUploadFilter',
    full_name='imageFilter.ImageFilterGrpc.ImageUploadFilter',
    index=1,
    containing_service=None,
    input_type=_IMAGEUPLOADGRPCREQUEST,
    output_type=_IMAGEFILTERGRPCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ImageLocalFilterAsync',
    full_name='imageFilter.ImageFilterGrpc.ImageLocalFilterAsync',
    index=2,
    containing_service=None,
    input_type=_IMAGELOCALASYNCGRPCREQUEST,
    output_type=_IMAGEREQUESTIDGRPCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ImageUploadFilterAsync',
    full_name='imageFilter.ImageFilterGrpc.ImageUploadFilterAsync',
    index=3,
    containing_service=None,
    input_type=_IMAGEUPLOADASYNCGRPCREQUEST,
    output_type=_IMAGEREQUESTIDGRPCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEFILTERGRPC)

DESCRIPTOR.services_by_name['ImageFilterGrpc'] = _IMAGEFILTERGRPC

# @@protoc_insertion_point(module_scope)
